// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1374271384067565518),
      name: 'AchievementEntity',
      lastPropertyId: const obx_int.IdUid(3, 2742028218823625374),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8771655310149993189),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5132939712054334440),
            name: 'achievementId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2742028218823625374),
            name: 'unlockedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7013063340276291450),
      name: 'ActivityLogEntity',
      lastPropertyId: const obx_int.IdUid(7, 7242354837289101868),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6478471990537975527),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3842356176060792788),
            name: 'wordId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6467024591852958562),
            name: 'tabName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7846030196715590676),
            name: 'score',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 716883683883350958),
            name: 'xpEarned',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 410949825746874427),
            name: 'durationSeconds',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7242354837289101868),
            name: 'timestamp',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 3588983662817578184),
      name: 'ChildEntity',
      lastPropertyId: const obx_int.IdUid(14, 4680712389311466001),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1236588667292561573),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1082947661506715368),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3241969920317064953),
            name: 'avatarEmoji',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2421773243469609354),
            name: 'ageBandStr',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2645401791628261601),
            name: 'xp',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5792068830773916444),
            name: 'level',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 402334987129145966),
            name: 'streakDays',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5203513343918447660),
            name: 'lastSessionDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2972478869206060886),
            name: 'hearts',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8973653967842256385),
            name: 'heartsLastRefill',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2684886413720721519),
            name: 'isPremium',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1275383567485264178),
            name: 'premiumExpiry',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 3029464117395726254),
            name: 'languageMode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4680712389311466001),
            name: 'selectedAvatar',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 6499829790914562177),
            name: 'wordProgress',
            targetId: const obx_int.IdUid(5, 6198316658734401237)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 7765431170856388706),
            name: 'activityLog',
            targetId: const obx_int.IdUid(2, 7013063340276291450)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(3, 6200940940522720377),
            name: 'achievements',
            targetId: const obx_int.IdUid(1, 1374271384067565518)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(4, 417922031944122408),
            name: 'stories',
            targetId: const obx_int.IdUid(4, 2467489899712539784))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 2467489899712539784),
      name: 'StoryEntity',
      lastPropertyId: const obx_int.IdUid(11, 2673766623130060804),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1224837305033813273),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9179474898004644414),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2244793699311472381),
            name: 'titleHi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8725441896812877578),
            name: 'heroName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3793591303214858853),
            name: 'setting',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9125462962102341243),
            name: 'problem',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7525622725661540925),
            name: 'scenesJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5755495411886905964),
            name: 'moralEn',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5987535152339585886),
            name: 'moralHi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 565141525158173450),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2673766623130060804),
            name: 'isShared',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 6198316658734401237),
      name: 'WordProgressEntity',
      lastPropertyId: const obx_int.IdUid(19, 8219291902732632445),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8517863362973093591),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9080207567398410385),
            name: 'wordId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2155211093048571768),
            name: 'meetComplete',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4546111364755800145),
            name: 'thinkComplete',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 656921766097306227),
            name: 'talkComplete',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6939399547001231795),
            name: 'writeComplete',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2153447064701168752),
            name: 'drawComplete',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 663642082969683471),
            name: 'storyComplete',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8237563429432124319),
            name: 'thinkScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8956412211385998575),
            name: 'talkScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 434323156348097246),
            name: 'talkClarity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1253992557651254300),
            name: 'talkAccuracy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 844980565231125264),
            name: 'talkFluency',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 2825051847420667293),
            name: 'writeScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2481267120146315617),
            name: 'drawScore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 4944998693523888034),
            name: 'starsEarned',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 7996419589131497725),
            name: 'totalXpEarned',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 8667855646582372196),
            name: 'attemptCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 8219291902732632445),
            name: 'lastAttempt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 6198316658734401237),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(4, 417922031944122408),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AchievementEntity: obx_int.EntityDefinition<AchievementEntity>(
        model: _entities[0],
        toOneRelations: (AchievementEntity object) => [],
        toManyRelations: (AchievementEntity object) => {},
        getId: (AchievementEntity object) => object.id,
        setId: (AchievementEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AchievementEntity object, fb.Builder fbb) {
          final achievementIdOffset = fbb.writeString(object.achievementId);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, achievementIdOffset);
          fbb.addInt64(2, object.unlockedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AchievementEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..achievementId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..unlockedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));

          return object;
        }),
    ActivityLogEntity: obx_int.EntityDefinition<ActivityLogEntity>(
        model: _entities[1],
        toOneRelations: (ActivityLogEntity object) => [],
        toManyRelations: (ActivityLogEntity object) => {},
        getId: (ActivityLogEntity object) => object.id,
        setId: (ActivityLogEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ActivityLogEntity object, fb.Builder fbb) {
          final wordIdOffset = fbb.writeString(object.wordId);
          final tabNameOffset = fbb.writeString(object.tabName);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, wordIdOffset);
          fbb.addOffset(2, tabNameOffset);
          fbb.addInt64(3, object.score);
          fbb.addInt64(4, object.xpEarned);
          fbb.addInt64(5, object.durationSeconds);
          fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ActivityLogEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..wordId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..tabName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..score =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..xpEarned =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..durationSeconds =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..timestamp = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));

          return object;
        }),
    ChildEntity: obx_int.EntityDefinition<ChildEntity>(
        model: _entities[2],
        toOneRelations: (ChildEntity object) => [],
        toManyRelations: (ChildEntity object) => {
              obx_int.RelInfo<ChildEntity>.toMany(1, object.id):
                  object.wordProgress,
              obx_int.RelInfo<ChildEntity>.toMany(2, object.id):
                  object.activityLog,
              obx_int.RelInfo<ChildEntity>.toMany(3, object.id):
                  object.achievements,
              obx_int.RelInfo<ChildEntity>.toMany(4, object.id): object.stories
            },
        getId: (ChildEntity object) => object.id,
        setId: (ChildEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ChildEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final avatarEmojiOffset = fbb.writeString(object.avatarEmoji);
          final ageBandStrOffset = fbb.writeString(object.ageBandStr);
          final languageModeOffset = fbb.writeString(object.languageMode);
          final selectedAvatarOffset = fbb.writeString(object.selectedAvatar);
          fbb.startTable(15);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, avatarEmojiOffset);
          fbb.addOffset(3, ageBandStrOffset);
          fbb.addInt64(4, object.xp);
          fbb.addInt64(5, object.level);
          fbb.addInt64(6, object.streakDays);
          fbb.addInt64(7, object.lastSessionDate?.millisecondsSinceEpoch);
          fbb.addInt64(8, object.hearts);
          fbb.addInt64(9, object.heartsLastRefill?.millisecondsSinceEpoch);
          fbb.addBool(10, object.isPremium);
          fbb.addInt64(11, object.premiumExpiry?.millisecondsSinceEpoch);
          fbb.addOffset(12, languageModeOffset);
          fbb.addOffset(13, selectedAvatarOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastSessionDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final heartsLastRefillValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final premiumExpiryValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26);
          final object = ChildEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..avatarEmoji = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..ageBandStr = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..xp = const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..level =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..streakDays =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..lastSessionDate = lastSessionDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastSessionDateValue)
            ..hearts =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0)
            ..heartsLastRefill = heartsLastRefillValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(heartsLastRefillValue)
            ..isPremium =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false)
            ..premiumExpiry = premiumExpiryValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(premiumExpiryValue)
            ..languageMode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 28, '')
            ..selectedAvatar = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 30, '');
          obx_int.InternalToManyAccess.setRelInfo<ChildEntity>(
              object.wordProgress,
              store,
              obx_int.RelInfo<ChildEntity>.toMany(1, object.id));
          obx_int.InternalToManyAccess.setRelInfo<ChildEntity>(
              object.activityLog,
              store,
              obx_int.RelInfo<ChildEntity>.toMany(2, object.id));
          obx_int.InternalToManyAccess.setRelInfo<ChildEntity>(
              object.achievements,
              store,
              obx_int.RelInfo<ChildEntity>.toMany(3, object.id));
          obx_int.InternalToManyAccess.setRelInfo<ChildEntity>(object.stories,
              store, obx_int.RelInfo<ChildEntity>.toMany(4, object.id));
          return object;
        }),
    StoryEntity: obx_int.EntityDefinition<StoryEntity>(
        model: _entities[3],
        toOneRelations: (StoryEntity object) => [],
        toManyRelations: (StoryEntity object) => {},
        getId: (StoryEntity object) => object.id,
        setId: (StoryEntity object, int id) {
          object.id = id;
        },
        objectToFB: (StoryEntity object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final titleHiOffset = fbb.writeString(object.titleHi);
          final heroNameOffset = fbb.writeString(object.heroName);
          final settingOffset = fbb.writeString(object.setting);
          final problemOffset = fbb.writeString(object.problem);
          final scenesJsonOffset = fbb.writeString(object.scenesJson);
          final moralEnOffset = fbb.writeString(object.moralEn);
          final moralHiOffset = fbb.writeString(object.moralHi);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, titleHiOffset);
          fbb.addOffset(3, heroNameOffset);
          fbb.addOffset(4, settingOffset);
          fbb.addOffset(5, problemOffset);
          fbb.addOffset(6, scenesJsonOffset);
          fbb.addOffset(7, moralEnOffset);
          fbb.addOffset(8, moralHiOffset);
          fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
          fbb.addBool(10, object.isShared);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = StoryEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..titleHi = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..heroName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..setting = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..problem = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..scenesJson = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..moralEn = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..moralHi = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0))
            ..isShared =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false);

          return object;
        }),
    WordProgressEntity: obx_int.EntityDefinition<WordProgressEntity>(
        model: _entities[4],
        toOneRelations: (WordProgressEntity object) => [],
        toManyRelations: (WordProgressEntity object) => {},
        getId: (WordProgressEntity object) => object.id,
        setId: (WordProgressEntity object, int id) {
          object.id = id;
        },
        objectToFB: (WordProgressEntity object, fb.Builder fbb) {
          final wordIdOffset = fbb.writeString(object.wordId);
          fbb.startTable(20);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, wordIdOffset);
          fbb.addBool(2, object.meetComplete);
          fbb.addBool(3, object.thinkComplete);
          fbb.addBool(4, object.talkComplete);
          fbb.addBool(5, object.writeComplete);
          fbb.addBool(6, object.drawComplete);
          fbb.addBool(7, object.storyComplete);
          fbb.addInt64(8, object.thinkScore);
          fbb.addInt64(9, object.talkScore);
          fbb.addInt64(10, object.talkClarity);
          fbb.addInt64(11, object.talkAccuracy);
          fbb.addInt64(12, object.talkFluency);
          fbb.addInt64(13, object.writeScore);
          fbb.addInt64(14, object.drawScore);
          fbb.addInt64(15, object.starsEarned);
          fbb.addInt64(16, object.totalXpEarned);
          fbb.addInt64(17, object.attemptCount);
          fbb.addInt64(18, object.lastAttempt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = WordProgressEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..wordId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..meetComplete =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false)
            ..thinkComplete =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false)
            ..talkComplete =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false)
            ..writeComplete =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false)
            ..drawComplete =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false)
            ..storyComplete =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false)
            ..thinkScore =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0)
            ..talkScore =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0)
            ..talkClarity =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)
            ..talkAccuracy =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0)
            ..talkFluency =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0)
            ..writeScore =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0)
            ..drawScore =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0)
            ..starsEarned =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0)
            ..totalXpEarned =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0)
            ..attemptCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0)
            ..lastAttempt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 40, 0));

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AchievementEntity] entity fields to define ObjectBox queries.
class AchievementEntity_ {
  /// See [AchievementEntity.id].
  static final id =
      obx.QueryIntegerProperty<AchievementEntity>(_entities[0].properties[0]);

  /// See [AchievementEntity.achievementId].
  static final achievementId =
      obx.QueryStringProperty<AchievementEntity>(_entities[0].properties[1]);

  /// See [AchievementEntity.unlockedAt].
  static final unlockedAt =
      obx.QueryDateProperty<AchievementEntity>(_entities[0].properties[2]);
}

/// [ActivityLogEntity] entity fields to define ObjectBox queries.
class ActivityLogEntity_ {
  /// See [ActivityLogEntity.id].
  static final id =
      obx.QueryIntegerProperty<ActivityLogEntity>(_entities[1].properties[0]);

  /// See [ActivityLogEntity.wordId].
  static final wordId =
      obx.QueryStringProperty<ActivityLogEntity>(_entities[1].properties[1]);

  /// See [ActivityLogEntity.tabName].
  static final tabName =
      obx.QueryStringProperty<ActivityLogEntity>(_entities[1].properties[2]);

  /// See [ActivityLogEntity.score].
  static final score =
      obx.QueryIntegerProperty<ActivityLogEntity>(_entities[1].properties[3]);

  /// See [ActivityLogEntity.xpEarned].
  static final xpEarned =
      obx.QueryIntegerProperty<ActivityLogEntity>(_entities[1].properties[4]);

  /// See [ActivityLogEntity.durationSeconds].
  static final durationSeconds =
      obx.QueryIntegerProperty<ActivityLogEntity>(_entities[1].properties[5]);

  /// See [ActivityLogEntity.timestamp].
  static final timestamp =
      obx.QueryDateProperty<ActivityLogEntity>(_entities[1].properties[6]);
}

/// [ChildEntity] entity fields to define ObjectBox queries.
class ChildEntity_ {
  /// See [ChildEntity.id].
  static final id =
      obx.QueryIntegerProperty<ChildEntity>(_entities[2].properties[0]);

  /// See [ChildEntity.name].
  static final name =
      obx.QueryStringProperty<ChildEntity>(_entities[2].properties[1]);

  /// See [ChildEntity.avatarEmoji].
  static final avatarEmoji =
      obx.QueryStringProperty<ChildEntity>(_entities[2].properties[2]);

  /// See [ChildEntity.ageBandStr].
  static final ageBandStr =
      obx.QueryStringProperty<ChildEntity>(_entities[2].properties[3]);

  /// See [ChildEntity.xp].
  static final xp =
      obx.QueryIntegerProperty<ChildEntity>(_entities[2].properties[4]);

  /// See [ChildEntity.level].
  static final level =
      obx.QueryIntegerProperty<ChildEntity>(_entities[2].properties[5]);

  /// See [ChildEntity.streakDays].
  static final streakDays =
      obx.QueryIntegerProperty<ChildEntity>(_entities[2].properties[6]);

  /// See [ChildEntity.lastSessionDate].
  static final lastSessionDate =
      obx.QueryDateProperty<ChildEntity>(_entities[2].properties[7]);

  /// See [ChildEntity.hearts].
  static final hearts =
      obx.QueryIntegerProperty<ChildEntity>(_entities[2].properties[8]);

  /// See [ChildEntity.heartsLastRefill].
  static final heartsLastRefill =
      obx.QueryDateProperty<ChildEntity>(_entities[2].properties[9]);

  /// See [ChildEntity.isPremium].
  static final isPremium =
      obx.QueryBooleanProperty<ChildEntity>(_entities[2].properties[10]);

  /// See [ChildEntity.premiumExpiry].
  static final premiumExpiry =
      obx.QueryDateProperty<ChildEntity>(_entities[2].properties[11]);

  /// See [ChildEntity.languageMode].
  static final languageMode =
      obx.QueryStringProperty<ChildEntity>(_entities[2].properties[12]);

  /// See [ChildEntity.selectedAvatar].
  static final selectedAvatar =
      obx.QueryStringProperty<ChildEntity>(_entities[2].properties[13]);

  /// see [ChildEntity.wordProgress]
  static final wordProgress =
      obx.QueryRelationToMany<ChildEntity, WordProgressEntity>(
          _entities[2].relations[0]);

  /// see [ChildEntity.activityLog]
  static final activityLog =
      obx.QueryRelationToMany<ChildEntity, ActivityLogEntity>(
          _entities[2].relations[1]);

  /// see [ChildEntity.achievements]
  static final achievements =
      obx.QueryRelationToMany<ChildEntity, AchievementEntity>(
          _entities[2].relations[2]);

  /// see [ChildEntity.stories]
  static final stories = obx.QueryRelationToMany<ChildEntity, StoryEntity>(
      _entities[2].relations[3]);
}

/// [StoryEntity] entity fields to define ObjectBox queries.
class StoryEntity_ {
  /// See [StoryEntity.id].
  static final id =
      obx.QueryIntegerProperty<StoryEntity>(_entities[3].properties[0]);

  /// See [StoryEntity.title].
  static final title =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[1]);

  /// See [StoryEntity.titleHi].
  static final titleHi =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[2]);

  /// See [StoryEntity.heroName].
  static final heroName =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[3]);

  /// See [StoryEntity.setting].
  static final setting =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[4]);

  /// See [StoryEntity.problem].
  static final problem =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[5]);

  /// See [StoryEntity.scenesJson].
  static final scenesJson =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[6]);

  /// See [StoryEntity.moralEn].
  static final moralEn =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[7]);

  /// See [StoryEntity.moralHi].
  static final moralHi =
      obx.QueryStringProperty<StoryEntity>(_entities[3].properties[8]);

  /// See [StoryEntity.createdAt].
  static final createdAt =
      obx.QueryDateProperty<StoryEntity>(_entities[3].properties[9]);

  /// See [StoryEntity.isShared].
  static final isShared =
      obx.QueryBooleanProperty<StoryEntity>(_entities[3].properties[10]);
}

/// [WordProgressEntity] entity fields to define ObjectBox queries.
class WordProgressEntity_ {
  /// See [WordProgressEntity.id].
  static final id =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[0]);

  /// See [WordProgressEntity.wordId].
  static final wordId =
      obx.QueryStringProperty<WordProgressEntity>(_entities[4].properties[1]);

  /// See [WordProgressEntity.meetComplete].
  static final meetComplete =
      obx.QueryBooleanProperty<WordProgressEntity>(_entities[4].properties[2]);

  /// See [WordProgressEntity.thinkComplete].
  static final thinkComplete =
      obx.QueryBooleanProperty<WordProgressEntity>(_entities[4].properties[3]);

  /// See [WordProgressEntity.talkComplete].
  static final talkComplete =
      obx.QueryBooleanProperty<WordProgressEntity>(_entities[4].properties[4]);

  /// See [WordProgressEntity.writeComplete].
  static final writeComplete =
      obx.QueryBooleanProperty<WordProgressEntity>(_entities[4].properties[5]);

  /// See [WordProgressEntity.drawComplete].
  static final drawComplete =
      obx.QueryBooleanProperty<WordProgressEntity>(_entities[4].properties[6]);

  /// See [WordProgressEntity.storyComplete].
  static final storyComplete =
      obx.QueryBooleanProperty<WordProgressEntity>(_entities[4].properties[7]);

  /// See [WordProgressEntity.thinkScore].
  static final thinkScore =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[8]);

  /// See [WordProgressEntity.talkScore].
  static final talkScore =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[9]);

  /// See [WordProgressEntity.talkClarity].
  static final talkClarity =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[10]);

  /// See [WordProgressEntity.talkAccuracy].
  static final talkAccuracy =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[11]);

  /// See [WordProgressEntity.talkFluency].
  static final talkFluency =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[12]);

  /// See [WordProgressEntity.writeScore].
  static final writeScore =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[13]);

  /// See [WordProgressEntity.drawScore].
  static final drawScore =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[14]);

  /// See [WordProgressEntity.starsEarned].
  static final starsEarned =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[15]);

  /// See [WordProgressEntity.totalXpEarned].
  static final totalXpEarned =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[16]);

  /// See [WordProgressEntity.attemptCount].
  static final attemptCount =
      obx.QueryIntegerProperty<WordProgressEntity>(_entities[4].properties[17]);

  /// See [WordProgressEntity.lastAttempt].
  static final lastAttempt =
      obx.QueryDateProperty<WordProgressEntity>(_entities[4].properties[18]);
}
